language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t caglargulmez/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true caglargulmez/docker-react npm run test -- --coverage
  
